version: "3"

services:
  web:
    image: hueidou/aspnetcorevue
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - jaeger
    environment:
      - MONGODB_CONNECTION=mongo:27017/wfteam
  jaeger:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "~/data/configdb:/data/configdb"
      - "~/data/db:/data/db"